### ISSUE TITLE
[Feature Request] - Create Channel Backups

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTL#122]
Provide a feature for backing up the channel for all and individual channels.
All channel backup api should be executed at the following instances:
1. When RTL server starts
2. When a new channel is opened by the user
3. When a channel is closed by the user

A `Backup` menu should be available under `Channels`.
The backup file should be created in the `backup` folder under RTL root. The folder location for saving backups can be over-ridden to a user preferred location, by an environment variable.
The file name for all channels should be `all-channels.bak`.
The file name for individual channels should be `channel-<channel id>.bak`

On the channel backup page, user should have the following options to execute for all and individual channels:
1. Create a backup
2. Verify a backup

API for channel backup is `GET /v1/channels/backup`
API for verifying channel backup is `POST /v1/channels/backup/verify`

![Channel Backups-4](https://user-images.githubusercontent.com/39208279/58762270-7204b380-851c-11e9-9e20-76df6327f191.png)

**Comment by ShahanaFarooqui** [comment]
Done, merged in master.

**Comment by ShahanaFarooqui** [comment]
@saubyk 
We took a slightly different approach to get the channel backup when RTL server starts. Rather than getting the backup at server start, we will not get the backup once the authenticated user opens the application from browser and requests for `getInfo` API.

It has been updated to above solution, to enable the RTL docker users and BTCPayserver users, to use RTL without setting admin.macaroon preemptively.

Referenced issues: #72 & #167
