### ISSUE TITLE
Failed to update in 0.3.0

### ISSUE THREAD

**Issue by babonet13** [ShahanaFarooqui/RTL#128]
My RTL 0.2.x version was succefully installed
I just tried to upgrade in 0.3.0, but I got this error after the command "node rtl"

==========================
satoshi@naka-dev:/src/RTL$ node rtl
Server is up and running, please open the UI at http://localhost:3000
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/src/RTL/logs/RTL.log'
==========================

And the web intertface at localhost:3000 is not reachable ...

**Comment by saubyk** [comment]
@babonet13 
It appears that RTL server is not able to create the log file, in the folder location where you have installed RTL, because of which the server is failing to start.

Can you please confirm, if you have upgraded from 0.2.x to 0.3.0 or installed 0.3.0 in a separate folder?

Also, why are you installing RTL in `/src` folder? The user you are running RTL with may not have permission to write in `/src` folder.

You can move the install to the user specific folder e.g. `/home/<user>/RTL` and it should work.

**Comment by babonet13** [comment]
I just followed your advice (install RTL in /home/satoshi instead of /src) ...
... and it works fine !
Thanks quick for support

**Comment by saubyk** [comment]
Glad. Happy to help. :-)
