### ISSUE TITLE
Add autopilot support

### ISSUE THREAD

**Issue by brmdbr** [ShahanaFarooqui/RTL#13]
It would be great if there was support for autopilot where you can configure it, and see what actions it has taken (channels/closed opened etc.).

**Comment by saubyk** [comment]
@brmdbr Couple of points to note about this:

- Its difficult to specifically figure out which channels are opened by Autopilot.
- Auto-pilot only opens and does not closes channels.
- Configuration of auto-pilot can be provided, but the problem is any modification to setting would require a LND re-start. Which we are currently not handling in the application.
- This requirement will be kept for future releases, as auto-pilot also needs to mature significantly.
- RTL is being built with a power user or a routing node operator in mind. And the assumption is the node operator is not depending on auto-pilot for managing channels.

Would be interested to hear your thoughts on this. Thanks.
