### ISSUE TITLE
Install prompts to send usage data to Google

### ISSUE THREAD

**Issue by tehelsper** [ShahanaFarooqui/RTL#172]
**Describe the bug**
While installing RTL, a prompt is displayed asking if the user would like to send anonymous usage data to Google. This makes installation via a script or automation difficult and appears to be newly introduced behavior. Installing the .3 betas did not have this prompt.

**To Reproduce**
1. Install RTL via npm

**Expected behavior**
RTL install successfully without any prompts.

**Actual behavior**
A prompt appears asking if the user will send usage data to Google.

**Screenshots**

Example:
...
> @angular/cli@8.1.2 postinstall /opt/mynode/RTL/node_modules/@angular/cli
> node ./bin/postinstall/script.js

? Would you like to share anonymous usage data with the Angular Team at Google under
Google’s Privacy Policy at https://policies.google.com/privacy? For more details and
how to change this setting, see http://angular.io/analytics. No

> node-sass@4.12.0 postinstall /opt/mynode/RTL/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /opt/mynode/RTL/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
...

**Additional context**
I use a script to install and upgrade RTL. The prompt makes handing automated upgrades very difficult.

**Comment by ShahanaFarooqui** [comment]
@tehelsper, thanks for raising the issue. We were kind of already worried about it before releasing 0.4.4 :). It is due to Angular upgrade from v7 to 8. Angular-cli already has the issue opened with Sev3:
https://github.com/angular/angular-cli/issues/14265

They have documented the commands to disable the prompt at:
https://github.com/angular/angular-cli/blob/f8fe4b0ee82d880396119a2594f3cee8dadb2947/docs/design/analytics.md#ci

For RTL analytics disabling: 
Go to /<RTLRootFolder>/node_modules/@angular/cli/bin folder and execute `ng analytics off'.

But, we understand that it can only be done after first installation of cli v8, which is not an ideal condition.

Another way to fix (for CI builds) is to set `NG_CLI_ANALYTICS` environment variable to false.
https://github.com/angular/angular-cli/issues/14563

So, currently we are trying to weigh in all of the above options. If none of them works then we will have to downgrade the version.

Please let us know if any of the above works for you. Thanks.

**Comment by ShahanaFarooqui** [comment]
@tehelsper, Another way to disable it in the script is to:

Install the angular-cli globally first. Before running 'npm install' command in the RTL root. By executing below command:
'npm install -g @angular/cli'

Then run 'ng analytics off -g'. It will set the angular-cli's analytics flag off even before running the npm install in the RTL.

Please check and let us know if that works for you. Thanks.

**Comment by tehelsper** [comment]
@ShahanaFarooqui Thanks! Executing "export NG_CLI_ANALYTICS=false" before installing RTL worked great!
