### ISSUE TITLE
Some Ideas to develop the UI

### ISSUE THREAD

**Issue by walterkok** [ShahanaFarooqui/RTL#38]
Hi Sauby_k, as discussed yday on Twitter here are my suggestions for improvement, hope they are useful. Regards Walter_K

First of all I like to mention that the RTL application is a very good, intuitive UI for the LND node. Well done to the team. I have installed it on the Raspberry PI where I have LND and Bitcoind running (thanks Stadicus!). I got stuck on lncli and RTL has really helped me to grap the basics so now lncli is much better to understand too. Ideal combi for me is to see the output of RTL and LND on putty sessions while using the RTL UI! I do have a couple of suggestions for improvements of the UI
1.	It looks like the server times out now and then, I have to log in again after a refresh. Is this a setting anywhere?
2.	I suggest to freeze the top part of the screen (the blue Ride The Lightning section and for example also the Add Channel menu below that in Channel Management) so that when you scroll down you continue to have a view on it and does not scroll away
3.	If you click on Menu [LND WALLET], it just unfolds this menu into two suboptions. I would show some content straight away (e.g. balance / latest transactions) as now the output screen does not refresh until you press a button below, eg [Send/Receive]. This is more responsive
4.	If you click on [List Transactions] under [LND WALLET] I suggest to sort the transactions with latest transaction date on top
5.	[PEERS] in add-peer inputfield I would specify lightning address (pubkey@ip:tcp) so it is clear what to enter instead of *
6.	[PEERS] it would be nice to add the location / country flag next to the IP address (e.g. ip.location.net) as it is a nice indication of where your peers are located
7.	[CHANNELS] if you click on this show something on the output screen like mentioned above
8.	[CHANNELS] [management] sort the channels Active on Top, Inactive on the bottom this avoids screening
9.	Same comment on locking the top part of the screen
10.	[PAYMENTS] show something in the output screen. I would combine the send_payment input here directly with the list payments so it is all on one screen. Latest payment listing on top. 
11.	So [PAYMENTS] would have no sub menu. 
12.	Lastly when you enter the payment date in the send_payment line you might consider that you show all the detail straight away in a pop up menu (rather than having to press decode) like Éclair has 
13.	In the [listpayments] menu it is interesting to see the number of hops. A little bit more detail there would be interesting. E.g I copied the PubKeys, entered them in 1ML.com, discovered the ip_address and found the location in ip.location.net. You might want to show the countries the payment went through
14.	[INVOICES] list them with the latest on top

**Comment by saubyk** [comment]
@walterkok  Thanks for providing this detailed feedback. Its definitely helpful.
We will be making a few improvements in the next release due in a day or two.
And, break down the rest of your inputs into individual tickets to further work on them.

Thanks.

**Comment by ShahanaFarooqui** [comment]
Thanks for the descriptive feedback, we are addressing the items you have raised per below:

It looks like the server times out now and then, I have to log in again after a refresh. Is this a setting anywhere?
[RTL]: It was the old setting to timeout the login after every 60 mins. Now, the setting has been changed and user will only be logged out if the session is idle for 60 min. Check Issue #40 for more details.

I suggest to freeze the top part of the screen (the blue Ride The Lightning section and for example also the Add Channel menu below that in Channel Management) so that when you scroll down you continue to have a view on it and does not scroll away
[RTL]: Locked the top menu bar as well as the table headers, but not planning to lock content cards as it may result in confusing UX for certain edge cases.

If you click on Menu [LND WALLET], it just unfolds this menu into two suboptions. I would show some content straight away (e.g. balance / latest transactions) as now the output screen does not refresh until you press a button below, eg [Send/Receive]. This is more responsive
[RTL]: Updated the menu links, so that the parent menu will redirect to the first child of the menu.

If you click on [List Transactions] under [LND WALLET] I suggest to sort the transactions with latest transaction date on top
[RTL]: Sorted on latest transaction dates.

[PEERS] in add-peer inputfield I would specify lightning address (pubkey@ip:tcp) so it is clear what to enter instead of *
[RTL]: Added the valid input format in placeholder.

[PEERS] it would be nice to add the location / country flag next to the IP address (e.g. ip.location.net) as it is a nice indication of where your peers are located
[RTL]: Opened Issue #42.

[CHANNELS] if you click on this show something on the output screen like mentioned above
[RTL]: Updated the menu links, so that the parent menu will redirect to the first child of the menu.

[CHANNELS] [management] sort the channels Active on Top, Inactive on the bottom this avoids screening
[RTL]: Sorted on active channels on top.

Same comment on locking the top part of the screen
[RTL]: Locked the top menu bar as well as the table headers, but not planning to lock content cards as it may result in confusing UX for certain edge cases.

[PAYMENTS] show something in the output screen. I would combine the send_payment input here directly with the list payments so it is all on one screen. Latest payment listing on top. So [PAYMENTS] would have no sub menu.
[RTL]: Combined both screens and removed decode section.

Lastly when you enter the payment date in the send_payment line you might consider that you show all the detail straight away in a pop up menu (rather than having to press decode) like Éclair has
[RTL]: Removed Decode button and model will show all the values.

In the [listpayments] menu it is interesting to see the number of hops. A little bit more detail there would be interesting. E.g I copied the PubKeys, entered them in 1ML.com, discovered the ip_address and found the location in ip.location.net. You might want to show the countries the payment went through
[RTL]: Opened Issue #41.

[INVOICES] list them with the latest on top
[RTL]: Sorted on latest on top.

**Comment by walterkok** [comment]
Hi guys, I downloaded the new SW and it all worked very well. Many thanks for the changes, great to see my ideas being realized !! Let me know if I can be of any help. Would be cool if we can release a version on the mainnet soon. Walter
