### ISSUE TITLE
Channels / Pending Channels

### ISSUE THREAD

**Issue by walterkok** [ShahanaFarooqui/RTL#50]
Hi all,
I have now been using RTL on the BTC mainnet and have one suggestion. I had to close down a channel (forced closing) and I noticed that this closing process does not get reflected well in my view in the UI. I learned through lncli that there was a pending channel, than going back to the RTL UI with pending channels I had to get to the pull-down menu on the right to show Pending Force Closing to show this status. More intuitive would be you see all the pending channel statuses in the bottom of the screen and add the indentifier there (rather than the pull down). So a list of all pending channels some of them are pending open, force closing, closing etc Thanks Walter

**Comment by saubyk** [comment]
Hi @walterkok 
The pending channel api returns a different sent of fields than list channels. Hence its not possible to show both the lists on the same page. Additionally, we feel that it might result in a highly cluttered page, since there are 4 different types of pending channel responses.

We are planning to address your concern in the following manner:
1. When a channel a closed, the confirmation message will indicate that pending channel page should be checked for status update.
2. The 'Pending' nav control on the Channel menu, will show a badge with the pending channel count, as long as you have any channel in the pending status.

**Comment by ShahanaFarooqui** [comment]
Fixed in release 0.2.14-beta. Thanks.
