### ISSUE TITLE
UI on Firefox Android

### ISSUE THREAD

**Issue by JeffVandrewJr** [ShahanaFarooqui/RTL#70]
A few minor issues when using RTL on Firefox on Android:

1. It's very difficult to paste a pubkey when trying to connect to a peer. The typical long press fails most of the time; it takes many attempts to get the paste menu to finally appear.

2. On the screen for connecting to peers and also opening channels, when the phone is held in portrait mode, buttons overlap. 

3. The side menu doesn't hide itself after making a selection. You have to double tap off of the menu to get it to slide away. This isn't necessarily apparent to the user; it took me a while to figure out how to get the menu to slide away.

**Comment by ShahanaFarooqui** [comment]
@JeffVandrewJr 
1: This issue is not related to RTL and cannot be fixed by us. It is more related to the browser and OS.
2: Peers page buttons overlapping has already been fixed in v0.2.14, Channel management and Lookup page overlapping are fixed in master branch, will be available in next release.
3: Side menu will now hide itself in mobile portrait mode, only when user clicks on child menu items. Clicking on parent menus will not hide the menu for obvious reasons. The fix is pushed in master and will be available with next release.
