### ISSUE TITLE
refunded balance still shown as timelocked

### ISSUE THREAD

**Issue by vamp111** [ShahanaFarooqui/RTL#83]
As seen on the picture, the balance of 3 force closed channels on the RTLapp is shown as timelocked althought it has already been refunded to my wallet and used to open another chanels. This can be prooved with the lncli listchaintxns command which lists the txid which can be checked and further followed within a blockexplorer

for example: closing txid 3005b8e30eb41f879d7a89c9eb624c8948bda4043604e216bf31a26e353983b2
refund pubkey: bc1q2w3etssvvnqp6akum795kkw7222ddxnwza7wk4  

https://www.smartbit.com.au/tx/3005b8e30eb41f879d7a89c9eb624c8948bda4043604e216bf31a26e353983b2

ends up here: bc1qaewx723cqugky27x3mpa6a54n7s3fpheh60yl0
and is used to fund another channel: 

https://www.smartbit.com.au/tx/5a65737eed478d0fe083786b8ca773ac770e558155ec178c69814201b6de8839

also simple channel ID gives error when pasted on the "lookups" but displays corretly on the 1ML.com explorer....
![rXIEDG7G](https://user-images.githubusercontent.com/40171661/54260679-e5280a80-4569-11e9-907d-8c248e2b9872.png)
![e5iFaRJ7](https://user-images.githubusercontent.com/40171661/54260688-eb1deb80-4569-11e9-91a7-8b515c08e778.jpg)
![ABPdJ6li](https://user-images.githubusercontent.com/40171661/54260692-ee18dc00-4569-11e9-8fb2-093ac5962380.jpg)

*im using RaspiBlitz which runs LND, ssh displays everything correct, however it seems that RTL doesnt.

**Comment by saubyk** [comment]
Hi @vamp111 
Couple of points to note here.

1. LND's closedchannels API provides the timelocked balance, in case of force closures, but does not provide the number of blocks for which the balance is locked. This should be addressed at LND level. I am not sure if a PR/Issue is open for the same. But it might be worth while to go through this issue. (https://github.com/lightningnetwork/lnd/issues/2562)
2. When you close the channel, I am guessing that LND removes the edge from its local copy of the network graph (since the channel is now closed). When you try to query the same channel, it will throw an error, because the channel does not exist. 1ml.com is clearly archiving the data, and keeping outdated network information on its databases, which you are able to query from.

You should note that we are not adding any significant functionality to what LND is offering. We are just providing an easy and organized way for you get the information directly out of your node. What you are getting on the UI, is what the LND API is returning, RTL is not keeping any local databases of its own, separate from LND.

Closing this issue with this explanation. Hoping this is helpful.
Feel free to open issues, if you find any other problems with RTL.

Thanks for trying out RTL.

**Comment by vamp111** [comment]
Hi,

your explanation is reasonable enought, LND told me they dont know why it shows like this, however when we track the onchain txns it shows that funds were returned

thanks, have a good one !
